version: "3"
services:
  rabbitmq:
    image: acr001cloudservices.azurecr.io/demo.layeredfactory.acquisition:rabbitmq-v.1.0
    ports:
     - "15672:15672"
     - "5672:5672"
     - "1883:1883"
    networks:
     - apps
    environment:
     - "RABBITMQ_DEFAULT_USER=node01"
     - "RABBITMQ_DEFAULT_PASS=node01"
    hostname: rabbitmq 
  dispatcher:
    image: acr001cloudservices.azurecr.io/demo.layeredfactory.acquisition.dispatcher:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - apps 
    depends_on:
       - rabbitmq
networks:
  apps:


